# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-devel

addons:
  apt:
    packages:
    - libgsl0-dev

warnings_are_errors: false
cache: packages

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

notifications:
  slack:
    secure: 2qqYomqZ1oMyyEbiwX3IsEUfIEDraE/sHD1igewBBv3915GpvkOBO9dFf8QzOVs7BxBLpRAFIcj8Z5Rx+tKJc38p4IjFrRsrnCCVlzMPUTPcQoCWOny9Ks9k3YESNwM3s0iOiXGpjpLWy5AxJhoqbpU0rOUm4HHO1j5Ya4HIOfGKESFlECp7BO1o5SZ5X63SeyyeaWd1j6sCPYFC98Nh57bTNVzs6DNdSyPAlSDzOtkNrHy2diRmKsT2mIkn3ci6Wj3XsLm+78+unZ4OjJNy/suy1oiTWuUYMcv8S7m7+znhaFs3KaY5OM37we/yvI7WcyB4HzmZpHL1AlHJv84NSVDS9LM8RZ03RNgTgd6+nlEjnelqElc+7Ulx9L7WZbaW6ed4zxilwWpgxGOEH6hmdDDHgw/lKXiXCU7xBuQ2GjTuoAWxAR71Kc1B0k5SZo76kX/Wfkm2NWUHaRQ3/mZdxdfKYgcXy1jZ6pOLVOW/apvEKlhvJ1iFrkLu/V8V3EonFLNEtQ5Age5Dbs90vgcNPQAGiav4G/F4v5jjK0qMrLjFVGUjyjSQ8JA3tPThexZWyrvsUES8hX5rCRtoONc43TnybfRRwFpm4jO5a1tcSqvkSA0XiwiVcTusKZws8fn0XzXfdLRRu8bFdhRqZ0RyWpJJEtuhHMF8ILs6d8WPrb8=

before_install:
    - Rscript -e 'install.packages("remotes")'

r_packages:
    - covr

after_success:
    - travis_wait 40 Rscript -e 'library(covr); codecov()'
